version: 0.2
phases:
  pre-build:
    commands:
      - echo "Entered build phase"
      - mvn clean prepare-package war:explode
  post-build:
    commnads:
      - echo "Entered the post-build phase"
      - mv target/deploy ./
artifacts:
  files:
    - deploy/**/*