version: 0.2
phases:
  pre_build:
    commands:
      - echo "Entered build phase"
      - mvn clean prepare-package war:explode
  post_build:
    commnads:
      - echo "Entered the post-build phase"
      - mv target/deploy ./
artifacts:
  files:
    - deploy/**/*